language: c

matrix:
        include:
                - os: linux
                  dist: xenial
                  sudo: true
                  compiler: gcc
                  addons: 
                        apt:
                                packages: build-essential libx11-dev libsdl2-dev cmake

script:
        - mkdir -p build
        - cd build
        - cmake ..
        - make
